### ISSUE TITLE
Master branch fails to install in python 3

### ISSUE THREAD

**Issue by greglever** [pycontribs/confluence#31] opened 2018-09-14 08:34 UTC
The `master` branch does not install via pip 18.0 in python 3.6.6:
```
(.venv) confluence$ git branch
  develop
* master
(.venv) confluence$ git fetch -p && git pull
Already up-to-date.
(.venv) confluence$ python --version
Python 3.6.6
(.venv) confluence$ pip --version
pip 18.0 from .venv/lib/python3.6/site-packages/pip (python 3.6)
(.venv) confluence$ pip install .
Processing confluence
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-h9ewyemm/setup.py", line 14, in <module>
        from confluence.version import __version__
      File "/tmp/pip-req-build-h9ewyemm/confluence/__init__.py", line 9, in <module>
        from version import __version__, __date__
    ModuleNotFoundError: No module named 'version'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-h9ewyemm/
```

but the `develop` branch installs fine:

```
(.venv) confluence$ git checkout develop && git fetch -p && git pull
Switched to branch 'develop'
Your branch is up-to-date with 'origin/develop'.
Already up-to-date.
(.venv) confluence$ pip install .
Processing confluence
Requirement already satisfied: pbr in .venv/lib/python3.6/site-packages (from confluence==0.0.1.dev52) (4.2.0)
Building wheels for collected packages: confluence
  Running setup.py bdist_wheel for confluence ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-8__8ht8u/wheels/dd/f8/57/5e3fc4895a1817b515e5b74c1f37327de8c70bb9244bb98ab8
Successfully built confluence
Installing collected packages: confluence
  Found existing installation: confluence 0.0.1.dev52
    Uninstalling confluence-0.0.1.dev52:
      Successfully uninstalled confluence-0.0.1.dev52
Successfully installed confluence-0.0.1.dev52
(.venv) confluence$ 
```

**Comment by paulwicking** [comment] 2018-09-16 06:19
Thanks for reporting this, @greglever. I'm not sure what's causing this for you, as I am unable to reproduce this myself. I notice that the version number you get (`confluence 0.0.1.dev52`) on the package is different from what I get (`confluence 0.0.1.dev62` for master and `[...].dev61` for develop), although I don't know why that happens. This could perhaps be the culprit?

If you want to investigate further, try cloning the repo to a new location, create a new virtualenv without site packages, and then install .

FWIW, I'm running debian buster and just installed added 3.6.6 this morning to pyenv. 

The following is my output from installing. First, the `master` branch:
```
paul@xps:~/source/python/test$ virtualenv --no-site-packages -p ~/.pyenv/versions/3.6.6/bin/python testenv
Running virtualenv with interpreter /home/paul/.pyenv/versions/3.6.6/bin/python
Using base prefix '/home/paul/.pyenv/versions/3.6.6'
New python executable in /home/paul/source/python/test/testenv/bin/python
Installing setuptools, pip, wheel...done.
paul@xps:~/source/python/test$ source testenv/bin/activate
(testenv) paul@xps:~/source/python/test$ python --version
Python 3.6.6
(testenv) paul@xps:~/source/python/test$ pip --version
pip 18.0 from /home/paul/source/python/test/testenv/lib/python3.6/site-packages/pip (python 3.6)
(testenv) paul@xps:~/source/python/test$ git clone git@github.com:pycontribs/confluence.git
Cloning into 'confluence'...
remote: Counting objects: 265, done.
remote: Total 265 (delta 0), reused 0 (delta 0), pack-reused 265
Receiving objects: 100% (265/265), 70.25 KiB | 329.00 KiB/s, done.
Resolving deltas: 100% (120/120), done.
(testenv) paul@xps:~/source/python/test$ cd confluence/
(testenv) paul@xps:~/source/python/test/confluence(master)$ git branch
* master
(testenv) paul@xps:~/source/python/test/confluence(master)$ git fetch -p
(testenv) paul@xps:~/source/python/test/confluence(master)$ git pull
Already up to date.
(testenv) paul@xps:~/source/python/test/confluence(master)$ pip install .
Processing /home/paul/source/python/test/confluence
Collecting pbr (from confluence==0.0.1.dev62)
  Using cached https://files.pythonhosted.org/packages/69/1c/98cba002ed975a91a0294863d9c774cc0ebe38e05bbb65e83314550b1677/pbr-4.2.0-py2.py3-none-any.whl
Building wheels for collected packages: confluence
  Running setup.py bdist_wheel for confluence ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-sebojtpf/wheels/90/c5/25/71914bf8a870212cda0c693fa344fa109e133058ee1833dc3d
Successfully built confluence
Installing collected packages: pbr, confluence
Successfully installed confluence-0.0.1.dev62 pbr-4.2.0
```
And then the `develop` branch:

```
(testenv) paul@xps:~/source/python/test/confluence(master)$ virtualenv --no-site-packages -p ~/.pyenv/versions/3.6.6/bin/python testdevenv
Running virtualenv with interpreter /home/paul/.pyenv/versions/3.6.6/bin/python
Using base prefix '/home/paul/.pyenv/versions/3.6.6'
New python executable in /home/paul/source/python/test/confluence/testdevenv/bin/python
Installing setuptools, pip, wheel...done.
(testenv) paul@xps:~/source/python/test/confluence(master)$ source testdevenv/bin/activate
(testdevenv) paul@xps:~/source/python/test/confluence(master)$ git checkout develop
Branch 'develop' set up to track remote branch 'develop' from 'origin'.
Switched to a new branch 'develop'
(testdevenv) paul@xps:~/source/python/test/confluence(develop)$ git fetch -p && git pull
Already up to date.
(testdevenv) paul@xps:~/source/python/test/confluence(develop)$ pip install .
Processing /home/paul/source/python/test/confluence
Collecting pbr (from confluence==0.0.1.dev61)
  Using cached https://files.pythonhosted.org/packages/69/1c/98cba002ed975a91a0294863d9c774cc0ebe38e05bbb65e83314550b1677/pbr-4.2.0-py2.py3-none-any.whl
Building wheels for collected packages: confluence
  Running setup.py bdist_wheel for confluence ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-4_j4dy73/wheels/90/c5/25/71914bf8a870212cda0c693fa344fa109e133058ee1833dc3d
Successfully built confluence
Installing collected packages: pbr, confluence
Successfully installed confluence-0.0.1.dev61 pbr-4.2.0
(testdevenv) paul@xps:~/source/python/test/confluence(develop)$ 
```

**Comment by greglever** [comment] 2018-09-17 07:52
ah thanks so much @wowsuchnamaste nuking the directory, making a new virtulenv and freshly cloning the repo did the trick !

**Comment by greglever** [comment] 2018-09-17 07:52
Do we know when this version is going to be released to pypi ?

**Comment by paulwicking** [comment] 2018-09-17 10:01
@greglever Glad to hear it got resolved! :) 

Regarding updating the content on pypi, the authentication vs pypi fails in Travis CI, this is a consequence of the update to pypi earlier this year. I believe @ssbarnea (or perhaps someone else in pycontribs?) has to get on it to fix that, as I am only a contributor, not maintainer.

I'm closing this issue for now, as it seems to be resolved.

**Closed as completed by paulwicking** 2018-09-17 10:01 UTC
