### ISSUE TITLE
WARNING:root:hostname 'companyid.jira.com' doesn't match either of '*.atlassian.net', 'atlassian.net' while doing GET

### ISSUE THREAD

**Issue by vaisov** [pycontribs/confluence#22] opened 2017-10-11 13:23 UTC
Recently started getting this error:

`WARNING:root:hostname 'companyid.jira.com' doesn't match either of '*.atlassian.net', 'atlassian.net' while doing GET https://companyid.jira.com/rest/api/2/serverInfo [{u'headers': CaseInsensitiveDict({'Accept-Encoding': 'gzip, deflate, compress', u'Accept': u'application/json,*.*;q=0.9', 'User-Agent': 'python-requests/2.2.1 CPython/2.7.6 Linux/4.4.0-93-generic', u'X-Atlassian-Token': u'no-check', u'Cache-Control': u'no-cache', u'Content-Type': u'application/json'}), 'params': None}] WARNING:root:Got ConnectionError [hostname 'companyid.jira.com' doesn't match either of '*.atlassian.net', 'atlassian.net'] errno:None on GET https://companyid.jira.com/rest/api/2/serverInfo {}\{} WARNING:root:Got recoverable error from GET https://companyid.jira.com/rest/api/2/serverInfo, will retry [1/3] in 17.9650767952s. Err: hostname 'companyid.jira.com' doesn't match either of '*.atlassian.net', 'atlassian.net`

> I have updated the real hostname to cover the our hostname.

**Comment by njbernstein** [comment] 2017-11-02 17:23
Any updates here? I'm having the same issue

**Comment by paulwicking** [comment] 2017-11-07 14:43
Is this an issue with the Confluence or Jira module?
What is the context for the error?

**Comment by vaisov** [comment] 2017-11-07 15:00
Both modules weren't working. Playing with upgrading pip packages - solved the issue. However it's now hard to track what was installed/upgraded to solve the issue. Anyway, the issue was solved by upgrading/installing pip packages. I think it was either `requests[security]` or `requests`

**Comment by paulwicking** [comment] 2017-11-08 07:01
Closing this issue as it was caused by `requests` and seems to be resolved there.

**Closed as completed** 2017-11-08 07:01 UTC
